### ISSUE TITLE
Permission denied: '/var/lib/pgadmin/sessions' error from running `docker compose up`

### ISSUE THREAD

**Issue by eleehiga** [felipewom/docker-compose-postgres#7]
From running `docker compose up` in this repository I encountered the same error as here: https://stackoverflow.com/questions/64781245/permission-denied-var-lib-pgadmin-sessions-in-docker. From the stack overflow post I had to run `sudo chown -R 5050:5050 pgadmin-data` in order to fix that error. Therefore, was wondering if you could please put this fix somewhere in the README or a setup script?

**Comment by felipewom** [comment]
Thanks for pointing that out! Using `sudo` can introduce security concerns, so it’s better to avoid it. Instead, we can handle this by using Docker volumes with the right permissions, running the container as the correct user, or making sure the host directory has the proper permissions before starting the container. Feel free to test these changes and, if you’re up for it, you can submit a PR with the README update. Appreciate your help!

**Comment by neederhow** [comment]
remove pgadmin-data/ and add `user: '$UID:$GID'` in docker-compose.yml work for me

```yaml
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    user: '$UID:$GID'
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/
```
